// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Indent = 1,
  Dedent = 2,
  blankLineStart = 13,
  Document = 3,
  String = 4,
  Plain = 5,
  Mapping = 6,
  Key = 7,
  MultiLine = 8,
  MultiLineKey = 9,
  MultiLineValue = 10
