// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {Indentation, trackIndent} from "./tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#rOQOQOOOOOO'#Ck'#CkO]OQO'#CbOOOO'#Cj'#CjQOOOOOOkOQO,58|OsOQO,58|OOOO,58|,58|O!OOQO'#CdOOOO'#Cm'#CmOOOO1G.h1G.hOkOQO1G.hO!TOPO,59OOOOO7+$S7+$SO!YOTO1G.jO!eOQO'#CgO!mOTO7+$UOOOO7+$U7+$UOOOP,59R,59ROOOP-E6e-E6eOOOO<<Gp<<Gp",
  stateData: "#Q~OSPOTPOVQO~OSPOTPOXWO`UO~ObXOcXO~OSPOTPOXWO~Ob[O~OP^O~OQaOY_OcaO~ObbOcbO~OQdOY_OcdO~OYXVS`VT~",
  goto: "!UbPPPPPPcPfPPlPPruP!ORROQVQRYUQ`^Rc`RSOQROQTQRZUQYTR]Z",
  nodeNames: "⚠ Indent Dedent Document String Plain Mapping Key MultiLine MultiLineKey MultiLineValue",
  maxTerm: 19,
  context: trackIndent,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "2R~RgOX!jXY&UYZ&wZp!jpq&Uqr!jrs&|tv!jvw#|wx,jxz!jz{#|{![!j![!]$j!]!`!j!`!a0t!a#p!j#p#q0t#q;'S!j;'S;=`&O<%l~!j~O!j~~1|~!qcYQT~OX!jXY#|Zp!jpq#|qr!jrs#|tv!jvx#|xz!jz{#|{![!j![!]$j!]!`!j!`!a#|!a#p!j#p#q#|#q;'S!j;'S;=`&O<%lO!j~$TTYQT~OY#|Zs#|t;'S#|;'S;=`$d<%lO#|~$gP;=`<%l#|~$scYQVPT~OX!jXY#|Zp!jpq#|qr!jrs#|tv!jvx#|xz!jz{#|{![!j![!]$j!]!`!j!`!a#|!a#p!j#p#q#|#q;'S!j;'S;=`&O<%lO!j~&RP;=`<%l!j~&_WYQ`PT~OX#|XY&UZp#|pq&Uqs#|t;'S#|;'S;=`$d<%lO#|~&|Ob~~'TZYQT~OY&|Z]&|]^#|^r&|rs'vst)Ot#O&|#O#P+Q#P;'S&|;'S;=`,d<%lO&|~(PVYQSPT~OY#|Zs#|t![#|![!](f!];'S#|;'S;=`$d<%lO#|~(oTYQVPT~OY#|Zs#|t;'S#|;'S;=`$d<%lO#|P)RXOY)OZ])O^r)Ors)ns#O)O#O#P){#P;'S)O;'S;=`*z<%lO)OP)sPSP![!])vP){OVPP*ORO;'S)O;'S;=`*X;=`O)OP*[YOY)OZ])O^r)Ors)ns#O)O#O#P){#P;'S)O;'S;=`*z;=`<%l)O<%lO)OP*}P;=`<%l)O~+XWYQT~OY&|YZ)OZs&|st)Ot;'S&|;'S;=`+q;=`<%l)O<%lO&|~+tYOY)OZ])O^r)Ors)ns#O)O#O#P){#P;'S)O;'S;=`*z;=`<%l&|<%lO)O~,gP;=`<%l&|~,q[YQT~OY,jZ],j]^#|^s,jst-gtw,jwx'vx#O,j#O#P/[#P;'S,j;'S;=`0n<%lO,jP-jXOY-gZ]-g^w-gwx)nx#O-g#O#P.V#P;'S-g;'S;=`/U<%lO-gP.YRO;'S-g;'S;=`.c;=`O-gP.fYOY-gZ]-g^w-gwx)nx#O-g#O#P.V#P;'S-g;'S;=`/U;=`<%l-g<%lO-gP/XP;=`<%l-g~/cWYQT~OY,jYZ-gZs,jst-gt;'S,j;'S;=`/{;=`<%l-g<%lO,j~0OYOY-gZ]-g^w-gwx)nx#O-g#O#P.V#P;'S-g;'S;=`/U;=`<%l,j<%lO-g~0qP;=`<%l,j~0}VYQXPT~OY#|Zs#|t}#|}!O1d!O;'S#|;'S;=`$d<%lO#|~1mTYQXPT~OY#|Zs#|t;'S#|;'S;=`$d<%lO#|~2ROc~",
  tokenizers: [Indentation, 0, 1],
  topRules: {"Document":[0,3]},
  tokenPrec: 86
})
